New
thelightreaper123/internship pull request #13
Opened 2023-07-27 23:45 UTC by thelightreaper123

2023-07-28 08:16 UTC, tayoogunbiyi approved these changes

2023-07-28 08:16 UTC, tayoogunbiyi commented on week6/src/App.js
> +  const storedTask = JSON.parse(localStorage.getItem('items')) || []
👍

2023-07-31 07:51 UTC, tayoogunbiyi requested changes
Please address the changes

2023-07-31 07:51 UTC, tayoogunbiyi commented on week6/src/App.js
> +          <List item={item} deleteit = {deleteitem}/><Link to={`/${item.value}`}><p>EXPAND</p></Link>
q: why did you switch from id to value?

2023-07-31 07:51 UTC, tayoogunbiyi commented on week6/src/Task.js
>    })
This doesn't work as expected. See the screenshot below

<img width="443" alt="Screenshot 2023-07-31 at 08 49 13" src="https://github.com/thelightreaper123/internship/assets/29612423/12029abc-e207-4332-ab9e-f6b4ef58d858">

2023-08-06 18:13 UTC, tayoogunbiyi approved these changes

2023-08-14 12:02 UTC, tayoogunbiyi requested changes

2023-08-14 12:02 UTC, tayoogunbiyi commented on week6/src/CreateTask.js
> +      alert('must contain at least one letter');
The alert says 'must contain at least ....' but does not make it clear that it is referred to the task name? 
Same thing as description below

2023-08-14 12:14 UTC, thelightreaper123 commented on week6/src/CreateTask.js
> +
I ran into an error when they were separated and moving it together fixed it

2023-08-23 10:23 UTC, tayoogunbiyi requested changes

2023-08-23 10:23 UTC, tayoogunbiyi commented on week6/src/App.js
> +   }
you didn't address this

2023-08-23 10:23 UTC, tayoogunbiyi commented on week6/src/App.js
> +   <CreateTask toggle={toggle} modal={modal}/>
neither did you address this

2023-08-23 10:23 UTC, tayoogunbiyi commented on week6/src/CreateTask.js
> +      <Modal isOpen={modal} toggle={toggle}>
you can see that 
1. the component is called Modal
2. you are passing a prop value called modal too. Could we name is isOpen instead? Apply this same process to the other places we use modal wrongly

2023-08-23 10:23 UTC, tayoogunbiyi commented on week6/src/CreateTask.js
> +          <textarea rows="2" className='form-control' value={time} onChange={e => setNewDate(e.target.value)}></textarea>
date shouldn't be a plain textarea. we can use a date picker instead - https://www.w3schools.com/tags/att_input_type_date.asp

2023-08-23 10:23 UTC, tayoogunbiyi commented on week6/src/CreateTask.js
> +          <textarea rows="2" className='form-control' value={time} onChange={e => setNewDate(e.target.value)}></textarea>
that will help with properly validating the date too

2023-09-04 05:10 UTC, tayoogunbiyi approved these changes

2023-09-10 03:21 UTC, merged